data:
    dataset: "data"
    patch_size: 64 
    num_workers: 32  
    data_dir: 'data/GRD1_2' 
    conditional: True

model:
    in_channels: 2
    out_ch: 4
    ch: 128 
    ch_mult: [1,2,3,4] 
    num_res_blocks: 2 
    attn_resolutions: [16,8] 
    dropout: 0.0
    ema_rate: 0.999
    ema: True
    resamp_with_conv: True

diffusion:
    beta_schedule: linear 
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 1000

training:
    patch_n: 16
    batch_size: 6
    n_epochs: 800 
    
    n_iters: 2000000 
    validation_epoch: 10

sampling:
    batch_size: 1
    last_only: True
    sample_type: generalized

optim:
    weight_decay: 0.000
    optimizer: "Adam" 
    lr: 0.00002 
    amsgrad: False
    eps: 0.00000001
    beta1: 0.9 
    beta2: 0.999
